### ISSUE TITLE
Allow partial search for Line numbers

### ISSUE THREAD

**Issue by pyrog** [Jungle-Bus/unroll#16]
Couldn't search all **TGV** or even **TGV*** lines.
Also, an autocomplete search could be fine for that 😃 

PS: partial search seem work for operators : **ra** find Yar**ra** Trams, Rostocker St**ra**ßenbahn AG, **RA**TB, **RA**TP…

**Comment by nlehuby** [comment]
> Couldn't search all TGV or even TGV* lines.

I'm not sure to understand :thinking: 
![image](https://user-images.githubusercontent.com/919962/96024260-ca0f3200-0e53-11eb-90cb-6fcfac9678f7.png)

what did you type in the search fields ?

**Comment by pyrog** [comment]
In the main page :

<img width="50%" alt="Search" src="https://user-images.githubusercontent.com/2158081/96035234-05fdc380-0e63-11eb-825c-dab0fcb1ed20.png">

**Comment by nlehuby** [comment]
"TGV" does not look like a relevant line number, it will work better in the other field :wink: 

partial search for line numbers won't work very well: when you are looking for the line "**1**", you don't want to learn about the line "**1**0", "2**1**" or "5**1**8" ...

**Comment by nlehuby** [comment]
I don't think it's a good idea to do a partial search on line numbers, I'm closing this one. Thanks for the feedback anyway
