### ISSUE TITLE
translating "hail and ride"

### ISSUE THREAD

**Issue by verdy-p** [Jungle-Bus/unroll#4]
I'm not sure about what you mean with this expression "hair and ride":

Do you mean that a section contains a set of possible stop positions spread across an area which can be reached on demand and causing the route to be adapted (effectively creating a "mesh" rather than a single linear section, e.g. anywhere inside a residential area, or village or suburb) beside the permanent stop positions (still useful for normal service so that people can wait the bus and get sure it will pass there even if they did not call before to make sure they'll have a bus passing there?

For me:
- "hail" is like the spread of small ice around storms: many possible impacts at random positions within an area.
- "ride" is strange, we are taking buses and travelling, we don't ride them, the driver will decide the route according to what he has the right to do within some limits (while also respecting a schedule within some acceptable margins so that other passengers will get to their destination in due time).

Or may be this is used for any "on demand" bus "lines/services" (similar to taxis, but there may be additional passengers and intermediate stops and no direct drive to the destination if there are more people that have called to be serviced). Most "on demand" bus services are made with mini-buses (often not more than 8 passengers plus the driver, and limited luggage that can be carried manually by a single person, or a wheelchair, or small carriers for babies).

Taxis may allow more luggages but should respect a direct route and won't stop to take more passengers when they are already in charge, unless their passenger explicitly allow it and ask to the driver to make an intermediate stop (these passengers have to agree to share the full drive, but the last passenger left will pay the taxi for everyone; in on-demand buses, every passenger pays their own fare separately to the driver, they are not responsible for the amount due by some passengers).

So clarify, and propably the English source is not really correct. And maybe it's colloquial in your area, but I did not find this expression anywhere in Google search or in any glossary or creative work. You seem to assume that people will understand it (like an image). That's why you used quotation marks around this expression. Please avoid it.

**Comment by nlehuby** [comment]
A "hail and ride" section is when the passenger can board or alight anywhere along the road by telling the driver (as opposed as only at the stops where signs exist).
![](http://1.bp.blogspot.com/-2Mw6MLFQIqE/VPT4asW403I/AAAAAAAATF4/i4pp9JLzyAY/s320/haride.jpg)

`ride` is actually quite used for public transport, see for instance the Park & Ride facilities (in French `parking relais`) or the Kiss & Ride areas (in French `dépose minute`). But I don't know about `Hail & Ride` usage, you may be right :thinking:  

`Hail and Ride` is the term used in OSM, that has been approved in 2018: https://wiki.openstreetmap.org/wiki/Proposed_features/hail_and_ride
Do you think we should explain it in Unroll ?
`There are some sections on this route with no fixed stops, where you can get on or off the vehicle by signalling the driver` or something like that ?

**Comment by verdy-p** [comment]
So this is a section with "stop on demand" (arrêt à la demande, appeler
pour s'arrêter).

I did not find this terminology used in OSM, the "proposed feature" page is
counter-intuitive, unapproved (only 10 users are aware of it and voted for
it in 2018, only 5 of them are active, then they made no effort to
document it better) as it was linked from nowhere and not announced in
relevant pages...

So this was probably made only for location in China/Hong Kong and may be
meaningful only for some British users. So yes you must explain.

Just like the terms "Kiss & Ride" which means nothing in French (certainly
not what you suppose, it is probably perceived as offensive, related to
sexual activity "riding").

Plese don't use these informal expressions thathave NO evident link to
transports on any of their terms (except "riding", but only if you're the
driver, not the traveller) !

**Comment by verdy-p** [comment]
Note that this vote on OSM wiki was not announced and it was closed too
early, I would have objected to the chosen term and tag. Such private vote
is INVALID

**Comment by verdy-p** [comment]
Also note that the justification for this expression is a single Wikipedia
page whose content is marked as needing verification since 2008 and that
was never updated, made by a single contributor (pure invention IMHO). And
in 2008 there was already the request to merge it into "Request stop".

That English Wikipedia does not have any interwiki link, only "Request
stop" is linked.

https://en.wikipedia.org/wiki/Request_stop

cs: Zastávka na znamení
de: Bedarfshalt
en: Request stop
eo: Laŭmenda haltejo
et: Nõudepeatus
nl: Stop op verzoek
pl: Przystanek na żądanie
simple: Request stop
sv: Request stop

So I'm right: the correct sentence is "This line has sections allowing
stops on demand" or "stops on request" (not just at signaled stops), as
long as it is at a safe place for such stop (e.g. in front of a parking
place or a exit from a private driveway, with a closed gate, or at a normal
stop of traffic light (but not on marked crossings), where there's a
protection or correct visibility, and only if the traffic conditions permit
it (does not block the traffic). This may be common in rural areas to avoid
passengers to walk for long distances along potentially unsafe narrow roads
with various passages with low visibility (curves with obscuring trees,
walls): the passenger entering or exiting this informal stop should be
visible for at least 50 meters away in urban areas, 150 meters in rural
areas (just like the general rules for normal signalization of dangers).

**Comment by verdy-p** [comment]
In France, we sometimes see this sentence on panels at official stops : "faire signed au chauffeur pour s'arrêter"; this means that the bus officially will pass there, but it will not stop unless there are passengers (waiting outside to board in, or that want to get out) signaling to the driver they want the bus to stop there. Passengers have to make visible a sign to the driver ("hail"), or ask him to stop in advance (they may use a button activating a light signal inside the bus, but most often they'll present themselves by getting beside the driver in the front of the bus, and will get out using the front door

Those passengers are regular users of the bus (e.g. children on way from/to their school) and they frequently recognize each other; however on most lines it is not permitted except in designated places where the stop position was first inspected and passengers have to make a demand to the municipality or intercommunality to instruct their demand and see if that place needs some modification or if another better place would be more suitable and more secure (not in the middle of a curve and when the road is large enough); the municipality may need to perform some works to stabilize the border and verify that this stop will not disturb neighbours (for example if the stop is in front of a private access driveway or garage exit, or if there are frequent trucks or the traffic by other vehicles on that place is too high and there's a risk of collisions with the bus or with passengers getting in/out).

This is common in very rural areas (e.g. a small hamlet or isolated dwelling or farm) where various stop positions, even if they are secured with a good visibility and an appropriate place for stoppping the bus without blocking the road, have most of the time no passengers waiting there for the bus, or wanting to get out.
